// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJF3C0t0cet2Qq7_1yUuitxHaxTWzEhsM',
    appId: '1:169639968348:web:959199a037a02e110ab099',
    messagingSenderId: '169639968348',
    projectId: 'hisaab-kitaab-24',
    authDomain: 'hisaab-kitaab-24.firebaseapp.com',
    storageBucket: 'hisaab-kitaab-24.appspot.com',
    measurementId: 'G-WMJ81CL6JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGHQ8w_euQzXhfz9_nZOvDzeQuzEvmkTk',
    appId: '1:169639968348:android:593703fcb24026810ab099',
    messagingSenderId: '169639968348',
    projectId: 'hisaab-kitaab-24',
    storageBucket: 'hisaab-kitaab-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClgvK_7AYpRDT1r8qy3v1XSU3_H0Ue3KA',
    appId: '1:169639968348:ios:8837ab7aa3b04a220ab099',
    messagingSenderId: '169639968348',
    projectId: 'hisaab-kitaab-24',
    storageBucket: 'hisaab-kitaab-24.appspot.com',
    iosBundleId: 'com.example.hisaabKitaab',
  );
}
